url:
  rails_homepage_url: "https://rubyonrails.org/"
  rails_tutorial_url: "https://www.railstutorial.org/"
  rails_help_url: "https://www.railstutorial.org/help"
  rails_book_url: "https://www.railstutorial.org/book"
  rails_contact_url: "https://www.railstutorial.org/contact"
  rails_news_url: "https://news.learnenough.com/"
  rails_screencasts_url: "https://screencasts.railstutorial.org/"
  learn_enough_url: "https://www.learnenough.com/"
  author_url: "https://www.michaelhartl.com/"
validate:
  length:
    length_80 : 80
    length_50: 50
    length_6: 6
    length_255: 255
    length_140: 140
  valid_email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
pagy:
  items_per_page: 30
mailer:
  from: "quangnam260800@gmail.com"
password_reset:
  expired_time: 2
micropost:
  image_type: ["image/jpeg", "image/gif", "image/png"]
  image_limit: [500, 500]
  accept_format: "image/jpeg,image/gif,image/png"
