url:
  rails_homepage_url: "https://rubyonrails.org/"
  rails_tutorial_url: "https://www.railstutorial.org/"
  rails_help_url: "https://www.railstutorial.org/help"
  rails_book_url: "https://www.railstutorial.org/book"
  rails_contact_url: "https://www.railstutorial.org/contact"
  rails_news_url: "https://news.learnenough.com/"
  rails_screencasts_url: "https://screencasts.railstutorial.org/"
  learn_enough_url: "https://www.learnenough.com/"
  author_url: "https://www.michaelhartl.com/"
validate:
  length:
    length_50: 50
    length_6: 6
    length_255: 255
  valid_email_regex: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
